#!/bin/sh

echo "Waiting ${INITIAL_DELAY:=60} seconds..."
sleep "${INITIAL_DELAY}"

while true; do
  /usr/bin/curator --config /home/ubuntu/elkstack/mn-1/curator/config.yml /home/ubuntu/elkstack/mn-1/curator/actions.yml

  echo "Sleeping ${PERIOD:=86400} until next run..."
  sleep "${PERIOD}"
done
