actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than $DELETE_AGE days (default is 3)
      for logstash and metricbeat prefixed indices.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
      exclude:
    filters:
    - filtertype: pattern
      kind: prefix
      value: decimal-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: ${DELETE_AGE}
      exclude:
      
