actions:
  1:
    action: snapshot
    description: the snapshot.
    options:
      repository: my_backup
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: 
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
      ignore_empty_list: True
#      remote_aws_key: ${AWS_KEY}
#      remote_aws_secret_key: ${AWS_SECRET}
#      remote_aws_region: ${AWS_REGION}
    filters:
    - filtertype: pattern
      kind: prefix
      value: *
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: ${DELETE_AGE}
      exclude:
      
  2:
    action: delete_indices
    description: >-
      Delete indices older than $DELETE_AGE days (default is 3)
      for logstash and metricbeat prefixed indices.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
      exclude:
    filters:
    - filtertype: pattern
      kind: prefix
      value: *
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: ${DELETE_AGE}
      exclude:
      
